### ISSUE TITLE
Can't install via pip: No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by Kriechi** [kiyo-masui/bitshuffle#66]
I tried to install the latest v0.3.3 on an Ubuntu 16.04, with the following error:

```
$ sudo pip3 instal bitshuffle
Collecting bitshuffle
  Downloading bitshuffle-0.3.3.tar.gz (232kB)
    100% |████████████████████████████████| 235kB 5.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_fovqf52/bitshuffle/setup.py", line 272, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by kiyo-masui** [comment]
Shoot. I'll fix this first thing this morning.

**Comment by Kriechi** [comment]
👍
